# Generated by Django 6.0.7 on 2026-09-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
